### ISSUE TITLE
get-schema and netconf-state/schemas for submodule retrieval

### ISSUE THREAD

**Issue by neoul** [vlvassilev/yuma123#10]
hi, vlvassilev.
Could you check this update for get-schema.

https://github.com/neoul/yuma123/commit/2d5ecce8a1d565c9005981e2ca426792a00706cf

The current yuma123 doesn't support the query for submodule schema file via get-schema rpc.
But, according to RFC 6022, the submodules should be also retrieved by get-schema and netconf-state/schema path.

**Comment by vlvassilev** [comment]
Fixed in 2.11
