### ISSUE TITLE
yuma123 :'When' conditional statements under 'choice' leaf are not validated correctly

### ISSUE THREAD

**Issue by sathishkchillout** [vlvassilev/yuma123#100]
I'm working with the multicast yang  bbf-mgmd.yang.
In that I'm trying to configure the ipv4-address leaf which is specified under ip-to-host choice leaf via yangcli.

   choice ip-to-host {
          when 'mode = "bbf-mgmd:proxy" or mode = "bbf-mgmd:snoop-'
             + 'with-proxy-reporting"';
          description
            "Provides the mechanism to add IP addressing information
             to the VPN. This data, if configured, shall be used in
             MGMD Membership Query messages sent on host interfaces.
             If not configured then the proxy or snooper with proxy
             reporting will generate MGMD Membership Query messages
             with the IP address 0.0.0.0 or the equivalent for IPv6.";
          case ip-address {
            leaf ipv4-address {
              when '../ip-version = "ipv4"';
              type inet:ipv4-address;
              default "0.0.0.0";
              description
                "The IPv4 address to be used as source IP address in
                 MGMD Membership Query messages when mode is proxy or
                 snoop-with-proxy-reporting.";
            }

According to the yang ,before configuring the ipv4-address leaf ,it will check for the ip-version and the proxy mode configured. I configured the correct proxy mode and ip-version only. 
I didn't get any error while giving the configuration for ipv4-address from yangcli .But when I tried to see the configuration done by get-conf command, the ipv4-address leaf is not shown.

when I'm checking the netconf.log ,found that while giving configuration , it is failing in validating the configured multicast  mode.
But i configured the mode as proxy only. (confirmed by the get-conf in yangcli)

Netoconf log
Get all instances of /baa-network-manager:network-manager/baa-network-manager:managed-devices/baa-network-manager:device/baa-network-manager:root/bbf-mgmd:multicast/bbf-mgmd:mgmd/bbf-mgmd:multicast-vpn/bbf-mgmd:ipv4-address
eval_expr
xpath result for '/baa-network-manager:network-manager/baa-network-manager:managed-devices/baa-network-manager:device/baa-network-manager:root/bbf-mgmd:multicast/bbf-mgmd:mgmd/bbf-mgmd:multicast-vpn/bbf-mgmd:ipv4-address'
  typ: nodeset =
   node bbf-mgmd:ipv4-address [L:9]

eval_expr mod:bbf-mgmd, line:674
xpath result for '../ip-version = "ipv4"'
  typ: boolean = true

val: when test '../ip-version = "ipv4"' OK for node '/baa-network-manager:network-manager/baa-network-manager:managed-devices/baa-network-manager:device[baa-network-manager:name='Broadcom_Altran_OLT']/baa-network-manager:root/bbf-mgmd:multicast/bbf-mgmd:mgmd/bbf-mgmd:multicast-vpn[bbf-mgmd:name='4100']' with context 'ipv4-address'
eval_expr mod:bbf-mgmd, line:663
xpath result for 'mode = "bbf-mgmd:proxy" or mode = "bbf-mgmd:snoop-with-proxy-reporting"'
  typ: boolean = false

val: when test 'mode = "bbf-mgmd:proxy" or mode = "bbf-mgmd:snoop-with-proxy-reporting"' failed for node '/baa-network-manager:network-manager/baa-network-manager:managed-devices/baa-network-manager:device[baa-network-manager:name='Broadcom_Altran_OLT']/baa-network-manager:root/bbf-mgmd:multicast/bbf-mgmd:mgmd/bbf-mgmd:multicast-vpn[bbf-mgmd:name='4100']' with context 'mgmd'
when_chk: test false for node 'bbf-mgmd:ipv4-address'
agt_acm: check write <ipv4-address> allowed for user 'root'
agt_acm: PERMIT (superuser)
Marking false when-stmt as deleted bbf-mgmd:ipv4-address

I tried by moving the 'when ' statements from choice ip-to-host  to  ipv4-address leaf as below.
By this way ,I am able to config the ipv4-address leaf  correctly.

       choice ip-to-host {
   /*       when 'mode = "bbf-mgmd:proxy" or mode = "bbf-mgmd:snoop-'
             + 'with-proxy-reporting"';
 */ **Moved this condition to ipv4-address leaf**
          description
            "Provides the mechanism to add IP addressing information
             to the VPN. This data, if configured, shall be used in
             MGMD Membership Query messages sent on host interfaces.
             If not configured then the proxy or snooper with proxy
             reporting will generate MGMD Membership Query messages
             with the IP address 0.0.0.0 or the equivalent for IPv6.";
          case ip-address {

            leaf ipv4-address {
/*
              when '../ip-version = "ipv4"';
*/**Changed as below**
               when '../ip-version = "ipv4" and ../mode[.= "bbf-mgmd:proxy" or .= "bbf-mgmd:snoop-with-proxy-reporting"]';
              type inet:ipv4-address;
              default "0.0.0.0";
              description
                "The IPv4 address to be used as source IP address in
                 MGMD Membership Query messages when mode is proxy or
                 snoop-with-proxy-reporting.";
            }

But we are adapted to a standard yang framework. So doing changes in  yang file is not a  advisable one.
How to validate the 'when ' conditions under 'choice' type leaf without changing the yang file.  
Whether yuma123 have support for validating the conditional statements under choice leaf?
[netconf.log](https://github.com/vlvassilev/yuma123/files/5894365/netconf.log)
Yang file
https://github.com/BroadbandForum/yang/blob/master/standard/networking/bbf-mgmd.yang

**Comment by lightside-instruments** [comment]
in short:

```
create /multicast/mgmd/multicast-vpn[name='123'] -- mode=snoop-with-proxy-reporting ipv4-address="1.2.3.4"
xget-config source=candidate /multicast/mgmd/multicast-vpn[name='123']/ipv4-address
...
rpc-reply {
  data {
  }
}
```

I will look into it.

**Comment by vlvassilev** [comment]
in short:

```
create /multicast/mgmd/multicast-vpn[name='123'] -- mode=snoop-with-proxy-reporting ipv4-address="1.2.3.4"
xget-config source=candidate /multicast/mgmd/multicast-vpn[name='123']/ipv4-address
...
rpc-reply {
  data {
  }
}
```

I will look into it.

**Comment by vlvassilev** [comment]
Fixed in https://github.com/vlvassilev/yuma123/commit/c4bd8037cacc4354698af2740b83db7dd76d01ae
