### ISSUE TITLE
Project lacks clear licensing information

### ISSUE THREAD

**Issue by troth** [vlvassilev/yuma123#103]
The licensing of the project is not clearly stated in a `LICENSE` or `COPYING` file. I can only assume that the project is BSD licensed by the statement in the `README` file.

This is problematic as I'm writing a Yocto/Openembedded recipe for yuma123 and recipes need to state not only the license information but a md5 hash of the license file (or relevant text). Adding a BSD `LICENSE` file for the project would be trivial and make it very easy for them writing Yocto recipes to properly provide license information so as to be in compliance of the license.

**Comment by vlvassilev** [comment]
Correct. I added symbolic link LICENSE->debian/copyright #fd17f6874c5e5f858ba181f7ec37bddb1499c91b which is the formal license specification according to the Debian requirements.

I am aiming at releasing a 2.12 version during the IETF 110 Hackathon 8-12 March. You can also package the 2.11 version which is the latest available in Debian.

**Comment by troth** [comment]
Works for me. Thanks!
