### ISSUE TITLE
XML Formation issue using Candid DB 

### ISSUE THREAD

**Issue by sathishkchillout** [vlvassilev/yuma123#109]
we are forming XML by using candidate db.
But seems order is Alphabetic order. Because of that Dependent object configuration  came later. 

   Is there way to retain user defined order

**Comment by vlvassilev** [comment]
The XML encoding of data is done according to the YANG module (not Alphabetic). In general implementations are required to order data only for RPCs and actions ( https://tools.ietf.org/html/rfc7950#section-7.5.7 )

You can control the order by editing the YANG module for example.

**Comment by sathishkchillout** [comment]
What order candid Db is stored ?

**Comment by vlvassilev** [comment]
The order specified in the YANG module.
