### ISSUE TITLE
call home support?

### ISSUE THREAD

**Issue by PeterYFPeng** [vlvassilev/yuma123#112]
I am working in 5G products. I need a netconf server to install into my devices.  The device need to support call home mode to connect to NMS. So that , Whether Yuma123 support call home setting?

**Comment by lightside-instruments** [comment]
You can implement call home by a simple shell script using mkfifo. Check this https://github.com/vlvassilev/yuma123/issues/74 .

**Comment by vlvassilev** [comment]
You can implement call home with a simple shell script using mkfifo. Check this thread
https://github.com/vlvassilev/yuma123/issues/74

**Comment by PeterYFPeng** [comment]
This is really helpful. Thank you very much.
