### ISSUE TITLE
load o-ran-operations.yang fault

### ISSUE THREAD

**Issue by PeterYFPeng** [vlvassilev/yuma123#113]
Loading YANG module from file:
  /usr/share/yuma/modules/O-RAN.WG4.MP-YANGs-v05.00/Common_Models/Operations/o-ran-operations.yang
yang_parse: Start module 'o-ran-operations' OK
xmlns_reg: id:51 mod:o-ran-operations	uri: urn:o-ran:operations:1.0
XPath fn current result: mod:o-ran-operations, line:127
xpath result for 're-match(current(), concat(/hw:hardware/hw:component/hw:mfg-name,
'_', /hw:hardware/hw:component/hw:model-name, '_',
/hw:hardware/hw:component/hw:serial-num ))'
  typ: nodeset = 
Segmentation fault (core dumped)

**Comment by vlvassilev** [comment]
These are probably minor issues. I can start by adding a testcase for the o-ran set of modules but I can not promise I can put fixing them very high on my priority list.

**Comment by vlvassilev** [comment]
Added a testcase and fixed this particular issue (in d44dbf4e0b8bde4cb40c1153359f5d72fd070968 ).
