### ISSUE TITLE
Multithreading support in Yuma123

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#12]
Hi vlvassilev,

Could you please let me know how many threads are supported in OpenYuma123 and how to check it out ?

As per my understanding, I could see that only one thread is supported by yuma123 frameworks. 
But, am just wondering how a single thread manages all such as configuration, notification, polling and etc. Could you please elaborate a bit on how all these are managed ? In case if a thread is busy on configuration then it cant send notification. Isn't it ? 

Thanks,
__Kals__

**Comment by vlvassilev** [comment]
Hi,

This is  correct. The design is of a classical Unix daemon with single select loop type. There is no provisioning  for callback handlers started in separate threads. Customization of the server code is needed for example to make it possible to send notifications while a lengthy <get> with time consuming virtual values are being processed.

Vladimir

**Comment by techkals** [comment]
Thanks Vladimir.

**Comment by techkals** [comment]
Hi Vladimir, please reply to my queries as am eagerly waiting for ur reply.
