### ISSUE TITLE
How to program an attribute which is depending on other attribute ?

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#13]
Hi vlvassilev,

Would like to know how dependency among attributes are handled in yuma123 ?

I see, each attribute has its own SIL function to be programmed into hardware. Assume the following scenario. A object has to be created with 3 attributes such as A1, A2 and A3. 
A1 is an optional attribute where as A2 and A3 are mandatory. Now, object creation SIL function has been called with A1. It can't be programmed without A2 and A3. But, A2 and A3 edit SIL functions (for creating them) are not called hence they are not programmed in the hardware so those values are not available. How to handle this situation on yuma123 ? 
Assume, A2 and A3 can't use default values as once the values are written on the hardware can't be reprogrammed.

Could you please let me know your thoughts on this ?

Thanks,
__Kals__

**Comment by vlvassilev** [comment]
Hi,

With attributes you refer to rfc7950 data nodes. This is a very common problem (I should add example of how this is handled). The mechanism of registration of callbacks per schema node only helps you avoid processing callbacks when irrelevant nodes B1, B2 change. However the A's can be in different top level containers so sometimes you need all the information from a configuration tree and not only the limited information provided by the direct parameters passed with the discrete calls of the edit callbacks.

You would access hardware in the commit phase e.g. cbtyp=AGT_CB_COMMIT. In that phase the changed config true; tree is already available and you can get the full runningcfg = cfg_get_config_id(NCX_CFGID_RUNNING); and access runningcfg->root. In case of complex data dependencies you might need to examine descendant nodes of several top containers to determine the correct action in the correct sequence regarding the southbound interface e.g. hardware register, cli etc.. The most flexible solution is to use val_clone_config_data  and keep a copy of the previous committed configuration tree. In your case you will have the same handler called as many times as necessary where you will configure the hardware during the first call and the rest will know that the cloned configuration is already identical and pass execution.

A good example would be a configuration where both a new interface and a route using the interface are created in the same commit. Even if the first commit phase callback is pointing to the created route one needs to create the interface and then the route e.g. (ifconfig followed by route) and not do anything in the second callback. So a callback registered for both should first handle interfaces reconfigurations then routes. I will add basic ietf-routing support to the current ietf-interfaces example SIL illustrating this.

Vladimir

**Comment by techkals** [comment]
Hi Vladimir,

Please rephrase my question.

1) A1 is an attribute which can be programmed only if A2 and A3 attributes are available.
As each attribute has its own SIL function for edit or any other operation, how the dependency is handled in OpenYuma frame-work ? Assume, you have got a call to program A1 where A2 and A3 has not already programmed ? How the dependency would be solved ?

2) Why can not have a single SIL function to program multiple attributes together ? 

3) What is the reason for having a separate SIL function for each of the attribute ?

Thanks,
__Kals__

**Comment by vlvassilev** [comment]
Hello,

If you want an atomic call per transaction you can use the agt_commit_complete API function. Here is example usage https://github.com/vlvassilev/yuma123/blob/master/netconf/test/netconfd/agt-commit-complete/test_agt_commit_complete.c part of a test case.

That said the _edit callbacks alternative provides an efficient way of detecting what changed and in some use cases allow for more efficient handling. Both mechanisms can be used together.

Vladimir

**Comment by techkals** [comment]
Thanks Vladimir for your info.

But, I am not able to find "test_agt_commit_complete.yang" file anywhere. 
Also, please let me know how to test this case ? 

Thanks,
Kals

**Comment by vlvassilev** [comment]
Hello,

When you do not specify full path or path with extension netconfd looks for either YANG module or SIL.
$ netconfd --module=test-agt-commit-complete
In this case there is a SIL compiled from the C file and it actually loads ietf-system.yang (I try to avoid writing custom modules when I can reuse standard ones). A SIL can potentially load and implement many YANG modules. You could alternatively have many SILs implementing a single YANG module etc.

To run testcases you will need to read the README (https://github.com/vlvassilev/yuma123/blob/master/netconf/test/netconfd/README) also see 
https://github.com/vlvassilev/yuma123/blob/master/netconf/test/platform-validation-scripts/debian_wo_pkgs.sh 

This script is what is used for daily builds and testing. Hope this helps.

Vladimir

**Comment by techkals** [comment]
Hi Vladimir,

Am using yuma123_2.10 version.

I dont see any yang file with the name of "test_agt_commit_complete.yang" . 
Is it a new piece of YANG file has been integrated into the latest code ? 

Also, am getting the below error while loading the module.

/usr/sbin/netconfd  --module=test-agt-commit-complete

Warning: SIL code for module 'test-agt-commit-complete' not found
Load module 'test-agt-commit-complete' failed (module not found)
Error: one or more modules could not be loaded
netconfd: init returned (operation failed)
Shutting down the netconfd server
 
In "atomic call per transaction" method, would multiple attributes i.e multiple leaf nodes be handled/programmed/verified in a single SIL function ? Can you please elaborate on this ? Am really stuck on this. Please help me out... Also, please reply to the below questions as well if you can...

2) Why can not have a single SIL function to program multiple leaf nodes/attributes together ?

3) What is the reason for having a separate SIL function for each of the attribute ?

Thanks,
Kals

**Comment by vlvassilev** [comment]
1. test-agt-commit-complete is a SIL part of the testcase. Gets installed with make ; make install and available as /usr/lib/yuma/libtest-agt-commit-complete.so If you did not 'make install' it is probably missing. The module parameter checks first for SIL and only then for YANG with the specified name. Which indeed can be confusing. I tend to use full paths when using YANG just to be sure no one installed SIL with duplicated name.

2. and 3.
What is "attribute"? You can register  _edit callback on the parent and the children and decide how you want to handle changes to the configuration.
