### ISSUE TITLE
Copy-config would do reprogramming ?

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#14]
Hi vlvassilev,

1) Will copy-config from any source (startup-config-db or candidate-config-db) to running-config-db would lead to reprogramming the hardware ?

running-config-db would be updated once config is programmed into the hardware through calling SIL functions. If configs are copied from startup-config-db to running-config-db then all the configs on running-db would be erased i.e would it call SIL functions to delete all the config ? then, as part of copy-config, would program the config into hardware through SIL functions ? This might lead to reprogramming  some of the config into the hardware. is nt it ?

2) Assume a situation where I have some config on candidate-db without commit i.e. the configuration changes are not yet committed into running-db. If i do copy-db from candidate to running-db, will those uncommitted configs also would be copied to running-db ?

Thanks in advance,
__kals__

**Comment by vlvassilev** [comment]
Hi,

Assuming you are already familiar with https://tools.ietf.org/html/rfc6241 and the :writable-running and :candidate capabilities ... I have not used netconfd with :writable-running and I have no test cases that validate it. yuma123 is concentrating on the classic transactional use of a candidate edits + <commit>. IMO a well supported :candidate capability is the proper way to implement NETCONF and I see no real value in maintaining :writable-running in addition to that.

Vladimir

**Comment by techkals** [comment]
Hi,

 want to access data from one container to another in OpenYuma code. How
can I do ?

Container Peer-1
|
|
list of sub-containers (Say A, B, C, D)
|
|
leaf state;

Question 1: Can A.leaf access B.leaf ? If so, how can access ?
Question 2: Can I achieve the above using XML config? Or XML config used
only for SET functions ? Can't be used for GET ?
Question 3: If I create another container say, Peer-2, can it access data
of Container-1 say, we want to access Peer1.A.leaf ? If so, how can we
access ?
