### ISSUE TITLE
yuam123 wiki not working 

### ISSUE THREAD

**Issue by srilchan81** [vlvassilev/yuma123#145]
Hi, 

yuma123 wiki is not working . 
https://[yuma123.org](https://yuma123.org/wiki/index.php/)/wiki/index.php/

Also hackathon link for alarms reference is also not working . 
https://www.[yuma123.org](https://www.yuma123.org/wiki/index.php/IETF_97_Hackathon_ietf-alarms_model_implementation_for_yuma123_report)/wiki/index.php/IETF_97_Hackathon_ietf-alarms_model_implementation_for_yuma123_report

regards
Srilekha

**Comment by vlvassilev** [comment]
Fixed. Was DNS problem. The majority of the documentation from the wiki is in netconf/doc/yuma_docs in mediawiki text files ... however the hackathon reports are not.
