### ISSUE TITLE
How to capture Netconf packets using wireshark

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#16]
Hi,

Could you please let me know how to capture Netconf packets in wireshark ?

- what should be wireshark version ?
- what is the filter has to apply ?

Thanks,
__kals__

**Comment by vlvassilev** [comment]
Hi,
Default NETCONF session would be XML datagrams sent over SSH. I guess you want to capture the XML and not the SSH packets so your only option is to configure either the server or the client side to dump the session.
For server side (netconfd or any other sshd subsystem a command piping the input and output streams can be configured in /etc/ssh/sshd_config:
...
Port 830
Subsystem netconf "/bin/sh -c 'tee /tmp/nc-`date +%s`-in.txt | /usr/sbin/netconf-subsystem | tee /tmp/nc-`date +%s`-out.txt'"

For client side (yangcli use the --dump-session option):
gdb --args yangcli --user=root --ncport=6830 --server=localhost --dump-session=/tmp/ncx-dump-

Vladimir

**Comment by techkals** [comment]
Hi Vladimir,

Thanks for your info. Yes, I would like to capture XML packet, not ssh packet. But, I would like to capture it in wireshark :(

Anyway, I tested with your commands.

The following command is not working for me.

Port 830
Subsystem netconf "/bin/sh -c 'tee /tmp/nc-date +%s-in.txt | /usr/sbin/netconf-subsystem | tee /tmp/nc-date +%s-out.txt'"

I don't see any files in the path...

Thanks,
Kals
