### ISSUE TITLE
Is there any problem if startup-config DB and running-config.DB are always same 

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#18]
Hi Vladimir,

What would be the problem, in case if startup-config-db and running-config-db are same always i.e whenever there is a change on running-db would be saved in startup-db also. So, will there be any problem due to this approach ?

Actually, i am seeing one problem here... in case if the node is crashed due to mis-configuration, it might go for continuous crash as startup-db and running-db is same. Assume, the mis-configuration has already been saved in running-db and would have been saved in startup-db.

Please let me know if you see any other problem apart from the above ?

Thanks,
__Kals__

**Comment by vlvassilev** [comment]
Hi,
This is the default behavior. The case where a configuration makes the system unresponsive can be handled with commit-confirmed (which is supported). Crashes (implementation bugs) usually happen before the commit is complete and running saved as startup. In the worse case scenario you will need some external script acting as watchdog restoring the startup configuration to known to work one. Of course the best solution is to avoid crashes which is easier with the YANG data validation then without.
