### ISSUE TITLE
Use of transaction id of startup-db

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#19]
Hi,

Am seeing transaction-id is also stored as storing startup-db.  

1) I would like to know what is the use of storing it ? 
2) Is it possible to replay the config based on the transaction id when system comes up ?

Does running-db also would store the transaction-id ?

Thanks,
Kals

**Comment by vlvassilev** [comment]
The .yuma/startup-cfg-txid.txt stores the incrementing configuration id of the running configuration when stored as startup. After reboot netconfd gets the current transaction id from that file and continues. There is nothing more to it.
