### ISSUE TITLE
How to build yuma123?

### ISSUE THREAD

**Issue by kostaz** [vlvassilev/yuma123#2]
There is no ./yuma123-git/autoreconf script.
There is no ./yuma123-git/configure script.
Here comes the question - how the heck to build this package???

**Comment by vlvassilev** [comment]
There is detailed description in ./yuma123-git/README and in

http://www.yuma123.org/wiki/index.php/Yuma_Installation_Guide#Building_and_Installation

On 05/17/2017 01:06 PM, kostaz wrote:
>
> There is no ./yuma123-git/autoreconf script.
> There is no ./yuma123-git/configure script.
> Here comes the question - how the heck to build this package???
>
autoreconf is a tool from the autoconf package. `autoreconf -i -f` 
generates  the configure script from configure.ac.
