### ISSUE TITLE
Accessing data from one container to another

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#22]
Hi,

I want to access data from one container to another in OpenYuma code. How can I do ? 
Container  Peer-1
   |
   |
   list of sub-containers (Say A, B, C, D)
     | 
     | 
     leaf state;
 
Question 1:  From SIL of A.leaf , can we access B.leaf ? If so, how can access ? 
Question 2:  Can I achieve the above using XML config? Or XML config used only for SET functions ? Can't be used for GET ?
Question 3: If I create another container say, Peer-2, can it access data of Container-1 say, we want to access Peer1.A.leaf ? If so, how can we access ? 

Thanks,
Kaliyaperumal K

**Comment by vlvassilev** [comment]
This is really confusing.
