### ISSUE TITLE
How to access all elements in a list without using index in Yuma123 ?

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#34]
Hi Vladimir,

This is regarding accessing all elements in a list in yuma123 without using index.

I knew, a particular element can be accessed using index/key in a list in yuma123.
There is a situation where i dont know the index but want to access all elements from the list. 
So, how can i access all elements from the list.  Is it possible ? If so, can you please let me know.  

Basically, how to access all elements in the list.

Thanks in advance.

**Comment by vlvassilev** [comment]
Use val_get_first_child and val_get_next_child . Used in  [mod_yangrpc_example.c](https://github.com/vlvassilev/yuma123/blob/master/netconf/src/yangrpc/libapache2-mod-yangrpc-example/mod_yangrpc_example.c)

**Comment by techkals** [comment]
Hi Vladimir,
Thanks for your answer. I have one more question.
1) val_get_next_child would work only for RO attributes or will it work for RW attributes also ? 
2) Does yang support "get_next" operation ? If so, how it is achieved ?

Thanks,
__kals__
