### ISSUE TITLE
How to access all elements in a Read Write container list without using index in Yuma123 ?

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#37]
Hi,

We know how to access Read-Only container elements, Is there any API to access Read-Write list elements without using the index.

I have referred mod_yangrpc_example.c file but here you are accessing Read-only elements. can you please let us know is there any way to access the list elements (Read-write).

Thanks,
Santhosh

**Comment by vlvassilev** [comment]
What you probably are looking for is the functions to create new values val_new_value(), initialize them to certain object template (YANG node type) - val_init_from_template(...) and add them as children to another container value - val_add_child(...) 

The are functions that are less processing efficient but easier to use e.g. 
res = val_set_cplxval_obj(statistics_val,statistics_val->obj,"<statistics><in-octets>12345</in-octets>...</statistics>")

The val_set_cplxval_obj functions fills a value from a xml string. And there are other functions user to fill data nodes.

**Comment by santhoshmaddikera** [comment]
My question is,
 If the **Read write** List (let say "L") entries are already configured via yangcli and I am now configuring a leaf object "X" in the yang which is not part of the list "L" via yangcli. In the Low level SIL code function of the leaf object "X", is it possible to access the list "L" entries which are already configured via yangcli ?

We know how to access **read-only** list entries in the SIL code level as in the **mod_yangrpc_example.c** file

**Comment by techkals** [comment]
Hi Vladimir,

can val_get_next_child () be used to retrieve RW attributes also ?

Thanks,
__kals__

**Comment by vlvassilev** [comment]
If "RW attribute" == "config=true data nodes" then yes.
