### ISSUE TITLE
What is the Reason for pattern match failed while loading module?

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#38]
Hi,

What is the Reason for pattern match failed while loading module?
yangcli root@localhost> mgrload IEEE8023-LAG-MIB

Warning: no revision statements for module 'IEEE8023-LAG-MIB'
Warning: Module 'ietf-inet-types' not used
IEEE8023-LAG-MIB.yang:22.3: warning(415): import not used

Warning: Module 'ietf-yang-types' not used
IEEE8023-LAG-MIB.yang:28.3: warning(415): import not used

Load module 'IEEE8023-LAG-MIB' OK

yangcli root@localhost> load IEEE8023-LAG-MIB

mgr_rpc: got invalid reply on session 1 **(pattern match failed)**
RPC Data Reply 12 for session 1:

rpc-reply {
  mod-revision
}

Thanks,
Santhosh

**Comment by vlvassilev** [comment]
One reason could be that your server does not have the same modules in its path as your client. Seems mgrload (client side) succeeds but not load (server side).

**Comment by santhoshmaddikera** [comment]
Thanks for your reply.

I have fixed warnings at mgrload. Then loaded. Working fine.
Is warnings will be impacted on loading errors ?

Thanks,
Santhosh
