### ISSUE TITLE
getting unknown namespace error for some leafs, module loaded successfully and able to create some other leaf in same module, what is the reason for unknown-namespace error?

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#39]
Hi,

Configuring object is leafref, the reference object is configured already in same module.

rpc-reply {
  rpc-error {
    error-type application
    error-tag unknown-namespace
    error-severity error
    error-app-tag data-invalid
    error-path /bridge-mib:BRIDGE-MIB/bridge-mib:fsQBridgeMIBObjects/bridge-mib:fsDot1qTp/bridge-mib:fsDot1qFdbTable/bridge-mib:fsDot1qFdbEntry[bridge-mib:fsDot1qVlanContextId='0'][bridge-mib:fsDot1qFdbId='12']/bridge-mib:fsDot1qVlanContextId
    error-message 'unknown namespace'
    error-info {
      error-number 266
    }
  }
}

reference object leaf contains "  smiv2:max-access  "not-accessible" "will it affect?

Thanks,
Santhosh

**Comment by vlvassilev** [comment]
I can try to look into the problem but you need to send me the XML of the edit-config RPC. If you use yangcli there is a new option --echo-requests you can use together with --display-mode=xml.

With older versions enable --log-level=debug4 and find the XML of the RPC.
