### ISSUE TITLE
Compilation Error for 2.11 release checkout

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#40]
Hi,

I facing below compilation error for 2.11 release code. could you please check and let me know the problem.

../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_agent_disconnect'
../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_agent_free'
../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_agent_get_identity'
../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_version'
../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_agent_userauth'
../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_agent_init'
../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_agent_connect'
../../../netconf/src/mgr/.libs/libyumamgr.so: undefined reference to `libssh2_agent_list_identities'
collect2: ld returned 1 exit status
make[1]: *** [yangcli] Error 1
make[1]: Leaving directory `/home/sathish/yuma123-2_11/netconf/src/yangcli'
make: *** [all-recursive] Error 1

Regards,
Santhosh

**Comment by vlvassilev** [comment]
What was the issue and how did you resolve it?
