### ISSUE TITLE
 make_sil_dir not installed in yuma123 ,

### ISSUE THREAD

**Issue by palaniace** [vlvassilev/yuma123#41]
Yuma123 not creating make_sil_dir .  I followed below steps . Yangcli  ,Yangdump , netconfd get installed but make_sil_dir not created.  To get install make_sil_dir what is the steps ?

===Option 2: Build from source===
sudo apt-get install git autoconf gcc libtool libxml2-dev libssh2-1-dev make libncurses5-dev zlib1g-dev libreadline-dev

git clone git://git.code.sf.net/p/yuma123/git yuma123-git
cd yuma123-git
autoreconf -i -f
./configure CFLAGS='-g -O0' CXXFLAGS='-g -O0' --prefix=/usr
make
sudo make install

**Comment by vlvassilev** [comment]
If you want to build a very basic SIL module (which is what make_sil_dir was doing) the easiest way is to take a working example and replace/edit the $mod.yang and $mod.c (check [helloworld](https://github.com/vlvassilev/yuma123/tree/master/example-modules/helloworld), [ietf-system](https://github.com/vlvassilev/yuma123/tree/master/example-modules/ietf-system), [ietf-interfaces](https://github.com/vlvassilev/yuma123/tree/master/example-modules/ietf-interfaces)

I do not use yangdump generated C templates but you can try generating with the same command make_sil_dir was using:

yangdump format=h indent=4 module=$mod output=$mod.h
yangdump format=c indent=4 module=$mod output=$mod.c

Vladimir
