### ISSUE TITLE
Issue in configuration via Yangcli, after loading the module

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#46]
Hi,

I have downloaded 2.11 version yuma123, and followed steps are per the README and compiled.
I have started netconfd and connected to yangcli session and load one module and SIL code.
When I tried to configure something using I am facing below error.

**Getting yang-library module set  ...
Current module-set-id: 7d4fedfaafebfdc28c5f4c91cb7b7a28a7deca97.

Checking Server Modules...

yangcli root@172.30.0.139> mgrload per-hop-behavior

Load module 'per-hop-behavior' OK

yangcli root@172.30.0.139> load per-hop-behavior

RPC Data Reply 2 for session 1:

rpc-reply {
  mod-revision 2018-03-04
}

yangcli root@172.30.0.139> create /PerHopBehavior/PerHopBehavior/
EgressExpCosMappingEntryList/   IngressCosExpMappingEntryList/  name
yangcli root@172.30.0.139> create /PerHopBehavior/PerHopBehavior/name

0.1: error(250): definition not found

Error: No object match for node 'PerHopBehavior' in expr '/PerHopBehavior/PerHopBehavior/name'
Error: definition not found ((in default parm) = /PerHopBehavior/PerHopBehavior/name)
Error in the parameters for 'create' command (definition not found)
yangcli root@172.30.0.139>**

can you please let me know how can I resolve this error.

Regards,
Santhosh

**Comment by vlvassilev** [comment]
You can either start netconfd with the module loaded at startup with the # netconfd --module=per-hop-behavior ... or you can disconnect and reconnect your yangcli session after dynamic load with yangcli> load per-hop-behavior

Both options will get you to a yangcli session that will not fail the create command you specify.

That said using mgrload has some implementation and some design issues. You can load YANG modules but if they contain data nodes (not only rpc and notifications) you are likely to encounter those issues.

Some details: The mgrload command is implemented in yangcli with additional module queue mgrloadQ not the one server module context is maintained in. There is also missing support for disabling features of the loaded modules. I will add "revision of the mgrload design and implementation" to the TODO list. I think in addition I will look also into adding support for ietf-yang-library notifications and update the server module queue dynamically.

Is dynamic module support high on your priority list?

**Comment by santhoshmaddikera** [comment]
Thank you Very much for your reply.

As you suggested we have the workaround. Since we are always doing dynamic module loading we are facing the problem. Closing and restarting the yangcli for every module loading is a little difficult. 

Yes, Dynamic module loading support is on highest priority, we are going to upgrade 2.11 version, I didn't face dynamic module support problem in 2.10.

Thanks and Regards,
Santhosh

**Comment by elena-604** [comment]
We are also considering dynamic module loading support as high priority for our design.

Regards,
Elena

**Comment by vlvassilev** [comment]
The dynamic loading support is there on the server side. No known issues for single YANG module and corresponding SIL pairs. The dynamic support of already connected yangcli clients has the only issue of the client having to reconnect .. for now.

**Comment by elena-604** [comment]
Thanks for the clarification, so if I have NMS connected using NETCONF will I still have this issue or it's yangcli specific?

**Comment by vlvassilev** [comment]
Should be no problem if the NMS handles the ietf-yang-library notifications and loads the module when it is received.

**Comment by elena-604** [comment]
Thanks!

**Comment by gouravgopal** [comment]
Please let me know if issue has been resolved as I can't see "revision of the mgrload design and implementation" in the TODO list.

**Comment by vlvassilev** [comment]
This [patch](https://github.com/vlvassilev/yuma123/commit/2c92b4b75ed86786bef5d671442fb50cc79a0025) fixes the mgrload issue.

**Comment by gouravgopal** [comment]
Thanks
