### ISSUE TITLE
/etc/yuma/ directory is not getting created with 2.11 version. The same working older version.

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#48]
Hi,

I am using 2.11 yuma123, yuma directory is not getting created with make and make install of 2.11 yuma123. Earlier I was using 2.2 openyuma where /etc/yuma/ directory is getting created.

I want to load the modules using netconfd.conf file.  This implementation is removed from latest yuma123?
Do we need to create that directory manually?

Thanks & Regards,
Santhosh

**Comment by vlvassilev** [comment]
Yes. You are free to use a configuration file but they are not created with 'make install'. For the moment there is no default configuration installed part of the debian 2.11 package either.
