### ISSUE TITLE
SIL code not generating for augmented leafs

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#49]
Hi,

Below l2vpn augment is doing from "qos.yang",  SIL code is not generating for "ingress-qos-template" grouping in both l2vpn and qos modules using make_sil_dir. 

augment "/l2vpn:l2vpn/l2vpn:instances/l2vpn:instance/l2vpn:endpoint/l2vpn:ac-or-pw-or-redundancy-grp/l2vpn:ac"
    {
       uses ingress-qos-template;
    }

Could you please let us know, SIL code will not be generated for augments? 

Regards,
Santhosh

**Comment by vlvassilev** [comment]
I do not use yangdump for generation of C templates. For me this is optional functionality and it is left at the state it was to be used as is. I can only help if you find problems in the core libyuma libraries and the netconfd and yangcli tools.
