### ISSUE TITLE
yangdiff and yangdump compilation issue

### ISSUE THREAD

**Issue by dragon01134** [vlvassilev/yuma123#5]
Making all in netconf/src/yangdiff
make[1]: Entering directory `/root/yuma123/netconf/src/yangdiff'
gcc -DPACKAGE_NAME=\"yuma123\" -DPACKAGE_TARNAME=\"yuma123\" -DPACKAGE_VERSION=\"2.10\" -DPACKAGE_STRING=\"yuma123\ 2.10\" -DPACKAGE_BUGREPORT=\"vladimir@transpacket.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"yuma123\" -DVERSION=\"2.10\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.  -I ../../../libtecla -I ../../../netconf/src/yangcli/ -I../../../netconf/src/agt -I../../../netconf/src/mgr -I../../../netconf/src/ncx -I../../../netconf/src/platform -I../../../netconf/src/ydump -I/usr/include/libxml2 -I/usr/include/libxml2/libxml -I../../../netconf/src/yangrpc -I../../../netconf/src/ydump   -g -O0 -g -fPIC -DDEBUG=1 -DLINUX=1 -DGCC=1 -DRELEASE=0 -DENABLE_DIRECT_MUST_AUGMENT_EX=1 -MT yangdiff-yangdiff.o -MD -MP -MF .deps/yangdiff-yangdiff.Tpo -c -o yangdiff-yangdiff.o `test -f '../../../netconf/src/yangdiff/yangdiff.c' || echo './'`../../../netconf/src/yangdiff/yangdiff.c
../../../netconf/src/yangdiff/yangdiff.c: In function ‘output_one_identity_diff’:
../../../netconf/src/yangdiff/yangdiff.c:645:44: error: ‘ncx_identity_t’ has no member named ‘baseprefix’
                                    oldident->baseprefix,
                                            ^
../../../netconf/src/yangdiff/yangdiff.c:646:44: error: ‘ncx_identity_t’ has no member named ‘baseprefix’
                                    newident->baseprefix,
                                            ^
../../../netconf/src/yangdiff/yangdiff.c:651:44: error: ‘ncx_identity_t’ has no member named ‘basename’
                                    oldident->basename,
                                            ^
../../../netconf/src/yangdiff/yangdiff.c:652:44: error: ‘ncx_identity_t’ has no member named ‘basename’
                                    newident->basename,
                                            ^

I got above error when i added yangdiff and yangdump compilation in Makefile.am. it seems fields are not there. But when i commented where ever it is used, it started compiling. and i got binaries. But i want to make sure is it ok or not, since i haven't gone through whole code so i am raising a issue.

**Comment by vlvassilev** [comment]
yangdiff and yangdump applications have to be updated to support YANG 1.1. In this case multibase identities require more then 1 basename and a list is introduced. But if you only plan to use YANG 1.0 with yangdiff fixing the compilation error should be trivial just use the first and only entry in the list. I have not planned any resources on maintaining yangdump and yangcli before the pending 2.10 release is complete (they are not part of the planned targets). I won't be able to look into this issue before next week.

**Comment by sweetheart01134** [comment]
In that case it's not possible to add support for a device with new yang module. Actually i came across this issue when i needed yangdump to create the .c files for my own module.

**Comment by vlvassilev** [comment]
The use of C template generation tools like yangdump is optional. All you need is a text editor to code the 3 public functions y_mymodule_init, y_mymodule_init2 and y_mymodule_cleanup to create a new SIL that can use the API to do anything. yangdump would create tons of constant definitions and unused callbacks. It is a nice to have tool but I do not use it. The examples yuma123-git/example-modules/ietf-* were written without the help of yangdump template.
