### ISSUE TITLE
yangcli session getting closed while minimize and maximizing putty

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#50]
Hi.

Please find below Queries, 
Query 1:
yangcli session getting closed while minimize and maximizing putty.

**yangcli root@localhost> Terminating: Interrupted system call**

Query 2:
  Can I start multiple netconfd servers and corresponding client sessions? in the same machine.
Eg:
  server 1    ----- yangcli
  server 2  ------- yangcli
 etc..

Regards.
Santhosh

**Comment by vlvassilev** [comment]
Query 1: I have seen this problem with certain combination of terminal settings and terminal handling libraries (libncurses and libreadline). I am not getting this on debian "stretch" but I will try to figure a way to reproduce it.

Query 2: Yes. As many as you have resources for.

**Comment by APCBoston** [comment]
Re: Query 2 -- I find it convenient to do this in Docker containers or `lxc` OS containers.  If you do it non-containerized on a single host you'd need to set different ports for the different server instances to listen on.  We have a base Docker image for this at https://hub.docker.com/repository/docker/chiashurb/netconfd/general (it's the result of taking an Ubuntu base image and running `apt update && apt install netconfd`; those operations take long enough when done several times per day that it was worth making a new image for it.)
