### ISSUE TITLE
How to get one attribute's value from another attribute-SIL function

### ISSUE THREAD

**Issue by techkals** [vlvassilev/yuma123#51]
Hi,
Please consider the following L2VPN schema tree.

container l2vpn
    container instances
      list instance
        leaf name
           . . . . . . . .
            case redundancy-grp
              **list primary-pw
                leaf name
              list backup-pw                                   ---------> How to access Primary-pw here ?
                leaf name**
              leaf protection-mode
              leaf revert
              leaf revert-delay
          leaf split-horizon-group

In this schema tree, I would like to get primary-pw name in backup-pw SIL. I could access the primary-pw name from OpenYuma-DB after "commit" phase. But, I need to access primary-pw name in validation phase itself. So, i can't get it from OpenYuma-DB. Could you please let me know if there is any other way ?
Thanks,
__kals__

**Comment by techkals** [comment]
Vladimir, can you please reply ?

**Comment by vlvassilev** [comment]
There are 2 different type of validations. 1. partial (edit-config targeting the candidate configuration) and 2 full (commit of candidate to running). In your case you want the commit time validation where relations of different data nodes in the configuration tree has to be validated.  Thus you need the second option and you want to ignore the partial validations.

1. Partial validation - you edit the candidate datastore you get this:
```
Breakpoint 1, edit_cb (scb=0x55555577fbc0, msg=0x555555775f10, cbtyp=AGT_CB_VALIDATE, editop=OP_EDITOP_REPLACE, newval=0x5555558acb80, curval=0x5555557763b0) at multiple-edit-callbacks.c:69
69	    char* editop_str=NULL;
(gdb) print *msg->rpc_txcb
$14 = {qhdr = {hdr_typ = 0, prev = 0x5555558ab1f0, next = 0x0}, txid = 96580, edit_type = AGT_CFG_EDIT_TYPE_PARTIAL, cfg_id = NCX_CFGID_CANDIDATE, apply_res = ERR_NCX_SKIPPED, commit_res = ERR_NCX_SKIPPED, 
  rollback_res = ERR_NCX_SKIPPED, start_bad = 85, rootcheck = false, commitcheck = false, is_validate = false, undoQ = {hdr_typ = 2727, prev = 0x55555589e288, next = 0x55555589e288}, auditQ = {hdr_typ = 2727, 
    prev = 0x55555589e2a0, next = 0x55555589e2a0}, deadnodeQ = {hdr_typ = 2727, prev = 0x55555589e2b8, next = 0x55555589e2b8}}
```

2. Full validation - upon <commit>
```
Breakpoint 1, edit_cb (scb=0x55555577fbc0, msg=0x5555558aca90, cbtyp=AGT_CB_VALIDATE, editop=OP_EDITOP_REPLACE, newval=0x555555899880, curval=0x5555558ab410) at multiple-edit-callbacks.c:69
69	    char* editop_str=NULL;
(gdb) print *msg->rpc_txcb
$15 = {qhdr = {hdr_typ = 0, prev = 0x7ffff766fc58 <main_arena+344>, next = 0x0}, txid = 96581, edit_type = AGT_CFG_EDIT_TYPE_FULL, cfg_id = NCX_CFGID_RUNNING, apply_res = ERR_NCX_SKIPPED, 
  commit_res = ERR_NCX_SKIPPED, rollback_res = ERR_NCX_SKIPPED, start_bad = 85, rootcheck = false, commitcheck = true, is_validate = false, undoQ = {hdr_typ = 2727, prev = 0x555555775f48, 
    next = 0x555555775f48}, auditQ = {hdr_typ = 2727, prev = 0x555555775f60, next = 0x555555775f60}, deadnodeQ = {hdr_typ = 2727, prev = 0x555555775f78, next = 0x555555775f78}}

```
As you can see you need to use msg->rpc_txcb->edit_type==AGT_CFG_EDIT_TYPE_FULL to check if both configurations are full.

When validating a commit you can either use curval (in running) and newval (in candidate) to access the corresponding configuration data. Or you could use cfg_get_config_id(NCX_CFGID_CANDIDATE) or cfg_get_config_id(NCX_CFGID_RUNNING) to get access to the root nodes and navigate from there.

You want all that flexibility in order to implement performance efficient validation.

There is another less flexible but much simpler alternative (i use this for simple cases) where you get the candidate configuration upon commit in a single callback call. You could use agt_commit_validate_register to add callback. :
```
...
            res=agt_commit_validate_register("mysil123",
                                  y_interfaces_interfaces_commit_validate);
...

status_t y_interfaces_interfaces_commit_validate(ses_cb_t *scb, xml_msg_hdr_t *msghdr, val_value_t *root)
{
    val_value_t *errorval = NULL;
    const xmlChar *errorstr = NULL;
    status_t res;

    log_info("in y_interfaces_interfaces_commit_validate\n");
            
    res = check_config(root, &errorval, &errorstr);
    if (res != NO_ERR) {
        agt_record_error(
            scb,
            msghdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            NCX_NT_STRING,
            errorstr,
            NCX_NT_VAL,
            errorval);
    }

    return res;
}

```

**Comment by vlvassilev** [comment]
That said in our latest products which are time sensitive network bridges we have models that do not need validation constrains that are not handled by YANG constrains or YANG deviation constrains (no description statement constrains). Thus we do not need to implement and test any validation callbacks.

**Comment by techkals** [comment]
Hi Viladimir,

Thanks for your response.

I have couple of basic questions.

1) When candidate database is not used, where the data would be saved
before "commit" ?
      For eg, the following SIL functions are called in sequence.

     SIL_Function_1 ()
        {
             leaf_integer_1 = 10;
         }

 SIL_Function_2 ()
        {
             leaf_integer_2 = 100;
         }

 SIL_Function_3 ()
        {
             leaf_integer_3 = 1000;
         }

May I know, where all these leaves would be stored before commit. If we
use, candidate DB, all these values would be stored on the candidate-DB. In
case, if we are not using where they are stored ?


2) In our implementation, we dont use candidate database. So, how can i
access "leaf_integer_1" value in  SIL_Function_3 () ?
I can access the value from running-database only after performing
"commit".
But, commit would be performed later i.e. am trying to access the value
before commit.

SIL_Function_1 ()
        {
            validation phase:
                  leaf_integer_1 = 10;
                  // *Where this value would be stored in case candidate DB
is not used?*
         }

 SIL_Function_2 ()
        {
            validation phase:
                    leaf_integer_2 = 100;
         }

 SIL_Function_3 ()
        {
            validation phase:
                     leaf_integer_3 = 1000;
                     *How to access leaf_integer_1 value here ?*
         }
// Assume all SIL functions would be executed in a single request.


Please clarify these questions.

thanks,
__kals__

**Comment by techkals** [comment]
Hi Viladimir,

Can you please reply to my question ?

Thanks,
Kaliyaperumal K

**Comment by vlvassilev** [comment]
I always use candidate + commit in our solutions. My observation is that many other solutions do that too. I know of no other NETCONF solution in production that does not use candidate + commit. You probably are using directly running and thus there is no point in the commit operation. I have no experience with that and no testcases to confirm if it is working or not. So if you are certain you want to continue not using candidate you are really on your own.
