### ISSUE TITLE
how we are loading the yang module and where it is storing after load of the yang module.

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#57]
We want to know how the yang module is working and where the yang information is stored.
Like i want to register the virtual node for read only leaf in yang.
How we can identify the type and walk all the leaf node and register the virtual node CB at the time of loading the module.

**Comment by vlvassilev** [comment]
Check the examples directory. The ietf-network-bridge OpenFlow implementation registers virtual node for /interfaces-state and reads the bridge statistics using OpenFlow protocol. There are other examples too like ietf-interfaces that uses virtual callback to get interface statistics available on the linux host.
