### ISSUE TITLE
Issue with includes at building

### ISSUE THREAD

**Issue by vggonzalez** [vlvassilev/yuma123#58]
Hi,

I'm trying to build yuma123, however I get this error message when I run the instruction $make:

ietf-network-bridge-openflow.c:31:10: fatal error: openvswitch/vconn.h: No such file or directory
#include <openvswitch/vconn.h>

I cloned this project which includes the required file and directory: https://github.com/openvswitch/ovs

But I still get the same error even though I explicitly included it in CLI ($make -I/ROUTE_TO_OPENVSWITCH/). I've also tried including this route in the Makefile but I'm not sure if I'm doing it okay.

Could someone help me?

**Comment by vlvassilev** [comment]
Remove the example/ietf-network-bridge target from the top Makefile.am or install openvswitch dev.

**Comment by vggonzalez** [comment]
Removing example/ietf-network-bridge was good enough, thank you very much, it's properly built now.

However I have one more question if you don't mind: I can see that in /usr/share/yuma/modules/ietf there's ietf-interfaces and in /usr/lib/yuma there are the .so modules for ietf-interfaces.
But when I start the netconfd server with $netconfd --module=ietf-interfaces.yang, it says "SIL code for module ietf-interfaces.yang not found". Isn't .so in the right path enough?
I can open a new issue for it if you want me to.

**Comment by vlvassilev** [comment]
You should not specify the extension (--module=ietf-interfaces works and loads the SIL named libietf-interfaces.so or prints warning if it does not find SIL but loads the YANG module ietf-interfaces*.yang if it finds one or fails if not) unless you specify full path. Use the full path if you want to load only the schema --module=/usr/share/yuma/modules/ietf/ietf-interfaces@2014-05-08.yang
