### ISSUE TITLE
Netconfd server not accepting connections

### ISSUE THREAD

**Issue by vggonzalez** [vlvassilev/yuma123#59]
Hi,

Everytime I try to connect to the netconfd server from yangcli I will get the message "session shut by remote peer" at yangcli logs, I can't start no session.

However, I can properly SSH to port 830 so it's not a configuration issue (sshd_config has been changed according to the wiki).

Any clue on this?

**Comment by vlvassilev** [comment]
What does the netconfd log say? You can get exactly this output from yangcli if you forgot to start netconfd.

**Comment by vggonzalez** [comment]
I've set netconfd log-level to debug4 and the same with yangcli. Netconfd won't return a single log after the connection attempt, however this is what yangcli returns:

Connect attempt with following parameters:
connect {
  user router
  server 192.168.56.101
  password ****
  ncport 830
  timeout 30
  public-key $HOME/.ssh/id_rsa.pub
  private-key $HOME/.ssh/id_rsa
  transport ssh
  tcp-direct-enable false
}
val->res is NO_ERR.

yangcli: Starting NETCONF session for router on 192.168.56.101
ses_msg: new out buff 0x558d56dd6f40 for s 0
mgr_ses: Got server authentication methods: publickey,password

**mgr_ses: SSH2 publickey authentication failed:
  libssh2 username/public key invalid
  key file was '$HOME/.ssh/id_rsa.pub'**

mgr_ses: password login succeeded
mgr sending hello on session 1
ses_msg: new out buff 0x558d56f73da0 for s 1
yangcli: Start session 1 OK for server 'default'
ses got send request on session 1
ses_msg_send full msg:
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
  </capabilities>
</hello>]]>]]>
mgr_ses: channel write 321 bytes OK on session 1 (a:0)<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
  </capabilities>
</hello>]]>]]>
mgr_io: read FD 3 for session 0 start
ses_accept_input on session 1
mgr_io: read FD 3 for session 0 start
ses_accept_input on session 1
mgr_io: read FD 3 for session 0 start
ses_accept_input on session 1
mgr_ses: read channel ses(1) ret(0)
mgr_ses: channel closed on session 1 (a:0)
**ses: session 1 shut by remote peer**

So after all seems like it's a ssh problem. Kinda shocking since I can ssh into port 830 with no problem.

**Comment by vggonzalez** [comment]
I fixed the SSH problem adding a generated key on the first computer on the authorized_keys file of the second computer. However, no netconf's session is getting established. Here is the log from yangcli (still no logs from netconfd):

Connect attempt with following parameters:
connect {
  user router
  server 192.168.56.101
  password ****
  ncport 830
  timeout 30
  public-key $HOME/.ssh/id_rsa.pub
  private-key $HOME/.ssh/id_rsa
  transport ssh
  tcp-direct-enable false
}
val->res is NO_ERR.

yangcli: Starting NETCONF session for router on 192.168.56.101
ses_msg: new out buff 0x5588e9646230 for s 0
mgr_ses: Got server authentication methods: publickey,password

mgr_ses: public key login succeeded
mgr sending hello on session 2
ses_msg: new out buff 0x5588e950aa60 for s 2
yangcli: Start session 2 OK for server 'default'
ses got send request on session 2
ses_msg_send full msg:
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
  </capabilities>
</hello>]]>]]>
mgr_ses: channel write 321 bytes OK on session 2 (a:0)<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
  </capabilities>
</hello>]]>]]>
mgr_io: read FD 3 for session 0 start
ses_accept_input on session 2
mgr_io: read FD 3 for session 0 start
ses_accept_input on session 2
mgr_io: read FD 3 for session 0 start
ses_accept_input on session 2
**mgr_ses: read channel ses(2) ret(0)
mgr_ses: channel closed on session 2 (a:0)**
ses: session 2 shut by remote peer
yangcli> 
mgr: shutdown requested
Terminating: Interrupted system call

**Comment by vlvassilev** [comment]
Seems before the password authentication was OK despite the publickey failing. So SSH authentication was never the problem.

My guess is there is a problem for sshd to execute the /usr/sbin/netconf-subsystem. You can skip sshd and emulate its behavior to figure what is going on (sshd does not log anything when it does not find subsystem executable!). Call the following command line (this is what sshd is supposed to do):

`export SSH_CONNECTION="192.168.56.101 830" ; export user=${USER} ; /usr/sbin/netconf-subsystem
`

You should get back:

```
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=file</capability>
    <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:partial-lock:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=trim,report-all,report-all-tagged</capability>
    <capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-08-06&amp;features=crypt-hash-md5,crypt-hash-sha-256,crypt-hash-sha-512</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2018-02-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2012-02-06</capability>
    <capability>urn:ietf:params:xml:ns:netconf:partial-lock:1.0?module=ietf-netconf-partial-lock&amp;revision=2009-10-19</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2011-06-01</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&amp;revision=2014-08-06&amp;features=radius,authentication,local-users,radius-authentication,ntp,ntp-udp-port,timezone-name,dns-udp-tcp-port</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-library?module=ietf-yang-library&amp;revision=2016-06-21</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
    <capability>http://netconfcentral.org/ns/yuma-app-common?module=yuma-app-common&amp;revision=2012-08-16</capability>
    <capability>http://netconfcentral.org/ns/yuma-mysession?module=yuma-mysession&amp;revision=2010-05-10</capability>
    <capability>http://netconfcentral.org/ns/yuma-ncx?module=yuma-ncx&amp;revision=2012-01-13</capability>
    <capability>http://netconfcentral.org/ns/yuma-proc?module=yuma-proc&amp;revision=2012-10-10</capability>
    <capability>http://netconfcentral.org/ns/yuma-time-filter?module=yuma-time-filter&amp;revision=2012-11-15</capability>
    <capability>http://netconfcentral.org/ns/yuma-types?module=yuma-types&amp;revision=2012-06-01</capability>
    <capability>http://yuma123.org/ns/yuma123-mysession-cache?module=yuma123-mysession-cache&amp;revision=2018-11-12</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01&amp;features=writable-running,candidate,confirmed-commit,rollback-on-error,validate,startup,url,xpath</capability>
    <capability>http://yuma123.org/ns/yuma123-netconf-types?module=yuma123-netconf-types&amp;revision=2017-06-23</capability>
    <capability>http://yuma123.org/ns/yuma123-system?module=yuma123-system&amp;revision=2017-03-26</capability>
    <capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2016-06-21&amp;module-set-id=017da2d3412a0b409b0b58e8ce3f3d803ae43a43</capability>
  </capabilities>
  <session-id>4</session-id>
</hello>]]>]]>
```

You can reply with:

```
<hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
 xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <capabilities>
   <capability>urn:ietf:params:netconf:base:1.0</capability>
 </capabilities>
</hello>]]>]]>
<rpc message-id="101"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get>
    <filter type="xpath" select="/"/>
  </get>
</rpc>]]>]]>
```

If this should work I suggest double checking the sshd_config file for typos. An alternative is to start dedicated sshd server per netconfd server instance.

**Comment by vggonzalez** [comment]
It was a typo. Sorry to bother you with this and thank you very much for your help.
