### ISSUE TITLE
In SIL code generation for union types not type casting, what is the reason ?

### ISSUE THREAD

**Issue by santhoshmaddikera** [vlvassilev/yuma123#60]
Hi,

I am generating SIL code for my code, it is having Union leaf as key.  But in SIL code generation for all other types typecasting happening except UNION types. Please find below piece of code.

const xmlChar *k_mplstp_oam_meg_meg_name = VAL_STRING(agt_get_key_value(errorval, &lastkey));
uint32 k_mplstp_oam_meg_lsp_spme_tunnel_id = VAL_UINT(agt_get_key_value(errorval, &lastkey));
xmlChar *k_mplstp_oam_meg_lsp_spme_local_lsr_id = agt_get_key_value(errorval, &lastkey);  ->UNION
xmlChar *k_mplstp_oam_meg_lsp_spme_remote_lsr_id = agt_get_key_value(errorval, &lastkey); ->UNION 

I have checked in netconf/src/ydump code, found below check,
boolean notunion = (obj_get_basetype(obj) != NCX_BT_UNION);
........
if (notunion) {
        write_c_val_macro_type(parms->scb, obj);
        ses_putchar(parms->scb, '(');
    }

May I know the reason why typecasting not doing for Union. 

Can I remove "notunion" check, if I remove, wil I get any error?

Regards,
Santhosh

**Comment by vlvassilev** [comment]
Auto generating code for union values would not be practical. Here a relevant fix.

https://github.com/vlvassilev/yuma123/commit/0d619ac10be961e6ff5b23244cefdeaaddafc68c

I also added testcase for yangdump C code generation that can be extended in future https://github.com/vlvassilev/yuma123/tree/master/netconf/test/yangdump/c
