### ISSUE TITLE
How to launch our own yuma yang module ?

### ISSUE THREAD

**Issue by anasov** [vlvassilev/yuma123#61]
Hello vladimir, I hope you are doing well,
We are begginers in all what concern yuma and yang module creation, we followed your wiki to create a client with yangcli and agent with netconfd and loaded the toaster module . The tutorial was sucessful in a sens that we had RPC OK in each of the tutorial steps .
Then we created our own module based on the toaster one, but we didn't know in which folder should we put our new created file.
We did a little bit of searching and we find that the modules were in a folder **"/usr/share/yuma/modules/netconfcentral"** we dropped our new module in this folder, and executed the netconfd command : **"/usr/sbin/netconfd --module=rhode-and-schwarz --superuser = minanas"** and then we get the following error : 

Starting netconfd...
Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
Copyright (c) 2013-2018, Vladimir Vassilev, All Rights Reserved.

Warning: SIL code for module 'rhode-and-schwarz' not found
Error: 'description' token not allowed here
Error:  Got 'description', Expected: anyxml, anydata, container, leaf, leaf-list, list, choice, uses,or augment keyword
rhode-and-schwarz.yang:23.11: error(246): wrong token value

Error:  Got 'leaf', Expected: keyword
rhode-and-schwarz.yang:27.9: error(246): wrong token value

Error:  Got 'TestModel', Expected: keyword
rhode-and-schwarz.yang:27.14: error(246): wrong token value

Error:  Got 'left brace, skipping to closing right brace', Expected: keyword
rhode-and-schwarz.yang:27.24: error(245): wrong token type

Error:  Got 'default', Expected: keyword
rhode-and-schwarz.yang:45.11: error(246): wrong token value

Error:  Got '3.2', Expected: keyword
rhode-and-schwarz.yang:45.19: error(245): wrong token type

Error:  Got 'semicolon', Expected: keyword
rhode-and-schwarz.yang:45.24: error(245): wrong token type

rhode-and-schwarz.yang:46.11: error(223): entry exists

Error: Extra input after end of module starting on line 50
rhode-and-schwarz.yang:50.5: error(281): extra node

Load module 'rhode-and-schwarz' failed (extra node)
Error: one or more modules could not be loaded
netconfd: init returned (operation failed)
Shutting down the netconfd server

E0:
   ../../../netconf/src/ncx/val.c:5830
   Error 2: NULL pointer

*** Total Internal Errors: 1 ***

Attached is the yang file that we created .

Thanks in advance for your help.

[rhode-and-schwarz.txt](https://github.com/vlvassilev/yuma123/files/3223185/rhode-and-schwarz.txt)

**Comment by vlvassilev** [comment]
You can install modules in /usr/share/yuma/<your-organization> everything under /usr/share/yuma is in the default search path.

Seems your YANG module is loaded but has errors.

If you want to develop SIL with implementation code for that module you should look into the examples directory where some standalone projects with dependency on installed yuma123 exist.

I recommend [ietf-interfaces](https://github.com/vlvassilev/yuma123/tree/master/example-modules/ietf-interfaces) and [ietf-network-bridge](https://github.com/vlvassilev/yuma123/tree/master/example-modules/ietf-network-bridge). A complete demo of how everything is expected to work in a mininet network environment can be found in the [netconfd/mininet](https://github.com/vlvassilev/yuma123/tree/master/netconf/test/netconfd/mininet) testcase

**Comment by vlvassilev** [comment]
There is bracket mismatch. In addition you use description statement inside input statement. According to RFC6020 this is not allowed.

You can use pyang to validate your module and format it pretty:
 
`pyang -f yang --path /usr/share/yuma/modules/ietf:/usr/share/yuma/modules/ietf-draft:/usr/share/yuma/modules/yuma123/ /usr/share/yuma/modules/rhode-and-schwarz/rhode-and-schwarz.yang`

Apparently pyang does not like non-unix line termination and does not detect the description statement in a YANG 1.0 module as problem. When you are done fixing the module the following command line works:

`/usr/sbin/netconfd --module=rhode-and-schwarz --no-startup`

**Comment by anasov** [comment]
Thank you so much for the very quick reply.
We managed to apply the advice you gave us . And our module validated by pyang and subsequently the module was able to be launched with netconfd.
For now, every successful operation that we perform returns only a message of the following type : **RPC OK Reply 12 for session 1** with no more details on what was written on the running database.
So we started analyzing a bit further the toaster module , and in the container section, we saw that the leaf toasterManufacturer , and toasterModelNumber do not contain in them the values that would later on be displayed by the command **xget /toaster** so the command returns the following :

Filling container /toaster: 
RPC Data Reply 7 for session 1: 

rpc-reply { 
   data { 
      toaster { 
         toasterManufacturer 'Acme, Inc.' 
         toasterModelNumber 'Super Toastamatic 2000' 
         toasterStatus up 
      } 
   } 
} 

Where did the module gets the values 'Acme, Inc' and 'Super Toastamastic 2000' since there are not written in the module itself .

Thank you so much for your assistance

**Comment by vlvassilev** [comment]
The toaster code is in libtoaster. The TOASTER-MIB never was the perfect example for YANG/NETCONF but is a OK starting point.

I am currently working on a testcase using mininet, https://github.com/vlvassilev/yuma123/tree/master/netconf/test/netconfd/mininet It is based on example-modules/ietf-interfaces and  example-modules/ietf-network-bridge SIL implementations.

**Comment by anasov** [comment]
Hello Vladimir,

After some trials and errors and some research, I tried to create my own SIL code in the .c file corresponding to the yang module. right now I'm trying to make the agent(server) send a customised RPC reply , so I created an rpc of type "output" in the yang module : 

rpc get-config-2 {
      output {
              leaf EVM {
              type string;   
              mandatory true;
              }
              leaf frequency {
              type string;
              }
        
      } 
    } 

I found somewhere on the internet that I should do the following : 

**For operations which return some data or <rpc-error>, the SIL code must do 1 of 2 additional tasks:
• add a val_value_t structure to the rpc_dataQ queue in the rpc_msg_t for each parameter listed in the YANG rpc 'output' section.
• set the rpc_datacb pointer in the rpc_msg_t structure to the address of your data reply callback function. See the agt_rpc_data_cb_t definition in agt/agt_rpc.h for more details.**

So I went to the .c file of the yang module, under the get-config-2 invoke function and did the following : 

**val_value_t *frequency_out = "hello from the other side";
dlq_enque(frequency_out,&msg->rpc_dataQ);** 

Needless to say , It didn't work and it shows me this warning during the make operation:

**warning: initialization from incompatible pointer type [enabled by default]
val_value_t *frequency_out = "hello from the other side";**

If I choose to ignore the warning and establish the connection between the client and the agent , after loading the module using "load rhode_and_schwarz", I type "get-config-2", following that is a connexion shutdown and the following message appears:

in the client prompt :"ses session 1 shut by remote peer"

In the agent side we get the follwing message :

"Session 1 for admin@127.0.0.1 now active (base:1.1)Segmentation fault (core dumped)"

I understand that the way I assigned the string to the variable in which the pointer frequency_out is pointing to is not the appropriate way to do it. But right now I'm really in an impass and I don't know how can I make my agent reply with a string of character.

I would really appreciate your help on the matter.

Thanks in advance.

Anasov

**Comment by vlvassilev** [comment]
Check the [helloworld](https://github.com/vlvassilev/yuma123/blob/master/example-modules/helloworld/helloworld.c) example. The message_val there is allocated and added to the data tree. In your case you will do the same but add the *_val to the RPC output data queue.

**Comment by anasov** [comment]
Thanks for your help.
