### ISSUE TITLE
Enquiry about current state and maintenance

### ISSUE THREAD

**Issue by JordiSubira** [vlvassilev/yuma123#68]
First of all sorry for posting it here, since it's not an issue, however I did not find any other support mail or mail list of yuma123 project on the wiki. I would really appreciate if some contributor can answer my questions.

Currently, I am working on a research project and I would need to implement support for NETCONF protocol. I consider Yuma123 as a candidate, but before going further and developing my application in order to integrate with Yuma123, I would truly appreciate if you can answer the questions as follows:

- Will Yuma123 be maintained within a near future?
- Are the team members available to answer technical question which might arise ?
- Are you planning to integrate bridging support with other languages?

Thank you very much and sorry for the possible inconvinience.

Best,
Jordi

**Comment by vlvassilev** [comment]
>     * Will Yuma123 be maintained within a near future?
Yes. lightside-instruments.com is a startup that will contribute further and maintain yuma123 under the same license conditions.
>     * Are the team members available to answer technical question which might arise ?
> 
Anything of relevance to the project published as issue on github will be addressed.
>     * Are you planning to integrate bridging support with other languages?
> 
Not on the server side. I use tntapi/litenc as client side python scripting solution with support for yangcli syntax that is using libyuma*.

**Comment by JordiSubira** [comment]
Really appreciate your response, thank you.

**Comment by APCBoston** [comment]
I'd like to propose this issue be marked "closed" as it does not have a live action item.  Perhaps this information could be posted on the main README or the wiki?
