### ISSUE TITLE
yangcli connect failed

### ISSUE THREAD

**Issue by xianyuesuifeng** [vlvassilev/yuma123#71]
yangcli> connect server=***** user=***** password=****
val->res is NO_ERR.

yangcli: Starting NETCONF session for admin on 10.87.21.4
mgr_ses: SSH2 establishment failed
yangcli: Start session failed for user admin on 10.87.21.4 (session failed)

yangcli> 

Using other yangcli to connect the same server is ok

**Comment by xianyuesuifeng** [comment]
centos 7.7

**Comment by vlvassilev** [comment]
1. Which version are you using (git hash number)?
2. What server are you testing against?
3. Try --log-level=debug4 (or lower level) to get a more detailed log information.
4. Try to get some information from the server too.
