### ISSUE TITLE
Does yuma123 support standalone listener application?

### ISSUE THREAD

**Issue by serega911** [vlvassilev/yuma123#72]
Hi @vlvassilev.

I see that provided examples (helloworld, toaster) are compiled together with netconf server (netconfd).

**Is it possible for existing application to receive notifications from netconf server?
Is there any examples?**

Thanks in advance,
    Sergii.

**Comment by vlvassilev** [comment]
Well with yangcli you can send 'create-subscription' and then all notifications are reported while you can continue sending RPCs. Are you looking for something simpler that does not need to handle concurrent RPCs, notifications and user IO?

**Comment by serega911** [comment]
@vlvassilev, thank for your reply.
Yes. I'm loking for creating new **client application**:

| NETCONF CLI |  <---> | NETCONF SERVER|   <---> | **CLIENT APPLICATION** |  <--->  | HARDWARE |

What I would like to do is to register in **client application** callbacks with agt_make_virtual_leaf() and agt_cb_register_callback().
Then, after datastore is changed, I want my callbacks to be called in the **client application**.

**Comment by vlvassilev** [comment]
The agt_* (agt_make_virtual_leaf, agt_cb_register_callback, agt_not_queue_notification_cb_register etc.) functions are only supported in SIL modules loaded in the context of the netconfd process.

If you want to have an external application (helper agent) you have to implement the inter-process communication between the registered callbacks in netconfd and the external application.

**Comment by serega911** [comment]
Thanks. Your help is very appreciated!
