### ISSUE TITLE
Identities and Unions for tab completion

### ISSUE THREAD

**Issue by dfedyk** [vlvassilev/yuma123#77]
Hi 
Tested a case where I have two identities. One set of identities has 2 values. the other set has 8.  I use a union of the two identities in a table.  When I configure in Yuma123 <tab> does not show the list (union of the identities) 
However if I combine the two identities in a single identity <tab> shows the list. 
The reason I broke them into two identities was the other place I used the identity I wanted just to have the smaller set for each case because the other values are not legal. (For the smaller identities config<tab> shows the members of the individual identities.)
So with one large identity set I get tab completion everywhere but the values are not always valid.
With two identities I get what I want but no tab completion for the union set. 
Why does a union of two identities not behave as one large identity for tab completion where for all intense purposes it is the same?  

I have made this work by creating a separate third identity that is a super-set by using similar names to the two sets but it seems to me that a union should have sufficed (it worked but you have to know the name of the identities whereas with a single identity  you get the names).  Imagine having to remember the 253 port types without tab completion.

Thanks.

**Comment by vlvassilev** [comment]
Added testcase [1c0ff88f](https://github.com/vlvassilev/yuma123/commit/387ac60fd0a51dc85e139660c995e3251c0ff88f) and implemented support for tab completion of unions [6e058a9f](https://github.com/vlvassilev/yuma123/commit/dde80db56624cda13de021e7d6a087276e058a9f).
