### ISSUE TITLE
Cross compilation issue

### ISSUE THREAD

**Issue by xkhavik** [vlvassilev/yuma123#78]
Hi Vladimir,

I was trying to cross compile yuma project for aarch64 target, please see example below 
./configure CFLAGS='-g -O0' CXXFLAGS='-g -O0' --target=aarch64 --host=aarch64 --build=x86_64 --prefix=/usr

Main problem is that .so libraries were not built.
"checking if libtool supports shared libraries... no"

Could you, please, give adviсe how to get necessary .so libraries during cross compilation?

**Comment by vlvassilev** [comment]
arm64 (aarch64) is supported and all debian packages build OK without any modifications  https://yuma123.org/repos/apt/debian/dists/stable/main/binary-arm64/Packages. The simplest solution would be to figure why your libtool installation does not support shared libraries and fix it.
