### ISSUE TITLE
netconfd crashes when sending connect from yangcli

### ISSUE THREAD

**Issue by aforester** [vlvassilev/yuma123#86]
Hello,

I am using yuma-master to try to understand a bit how all these work.
Using CentOS 7.8 VM, where I managed to compile and install all.
I can start netconfd without problems, apparently yangcli as well, but not so sure (will see why).
I will attach the logs for both programs. The main idea is that neconfd crashes when I try "connect" from yangcli, no matter if I load helloworld or toaster modules (see netconfd-crash.txt).
Now, yangcli seems to have some concerning messages when started, I don't know if they are important or not:

xmlns_reg: id: 1 mod:yuma-ncx   uri: INVALID
...................................
Attempting to load module 'yuma-types'
ncxmod: Using module 'yuma-types' already loaded
ncxmod: could not open directory '/home/alip/modules/'
...................................

Then this happens:

Connect attempt with following parameters:
input {
  server localhost
  ncport 22
  private-key /home/alip/.ssh/id_rsa
  public-key /home/alip/.ssh/id_rsa.pub
  use-agent true
  transport ssh
  tcp-direct-enable false
  timeout 30
  user alip
  password ****
}

val->res is NO_ERR.
yangcli: Starting NETCONF session for alip on localhost
ses_msg: new out buff 0x1df07b0 for s 0
mgr_ses: Got server authentication methods: publickey,gssapi-keyex,gssapi-with-mic,password

mgr_ses: SSH2 failure connecting to ssh agent
mgr_ses: SSH2 trying next authentication method
mgr_ses: SSH2 publickey authentication failed:
  libssh2 username/public key invalid
  key file was '/home/alip/.ssh/id_rsa.pub'

mgr_ses: password login succeeded
mgr sending hello on session 1
ses_msg: new out buff 0x1e15390 for s 1
yangcli: Start session 1 OK for server 'default'
ses got send request on session 1
ses_msg_send full msg:

...and the rest of the log.

Can you give some hints why is this crash happening? Is in any way related to the ssh2 errors, although the ssh session in the end seems successful?
Any help is greatly appreciated! 
Best regards,
Alin
[netconfd-crash.txt](https://github.com/vlvassilev/yuma123/files/4735567/netconfd-crash.txt)
[yangcli-ouput.txt](https://github.com/vlvassilev/yuma123/files/4735569/yangcli-ouput.txt)

**Comment by aforester** [comment]
I mixed up a bit the crashes, they are not the same for toaster, this is the crash when using toaster module:

:~>/usr/sbin/netconfd --superuser=alip --log=/home/alip/yumalogs --module=toaster --startup=/tmp/startup-cfg.xml &
[1] 28527
:~>
:~>cat /home/alip/yumalogs

*** log open at 2020-06-05T11:55:05Z ***
Starting netconfd...
Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
Copyright (c) 2013-2018, Vladimir Vassilev, All Rights Reserved.

agt: Startup config loaded OK
     Source: /tmp/startup-cfg.xml

Running netconfd server (2.12-0)
:~>
[1]+  Segmentation fault      /usr/sbin/netconfd --superuser=alip --log=/home/alip/yumalogs --module=toaster --startup=/tmp/startup-cfg.xml
:~>
:~>cat /home/alip/yumalogs

*** log open at 2020-06-05T11:55:05Z ***
Starting netconfd...
Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
Copyright (c) 2013-2018, Vladimir Vassilev, All Rights Reserved.

agt: Startup config loaded OK
     Source: /tmp/startup-cfg.xml

Running netconfd server (2.12-0)

New session 1 created OK
agt_connect error (access denied)
  dropping session 1
E0:
   ../../../netconf/src/agt/agt_sys.c:944
   Error 4: invalid internal value

Session 1 closed:~>

BR,
Alin

**Comment by vlvassilev** [comment]
My guess is your netconfd has different --port=<portnum> parameter (830 if the option is not present) then the "Port <portnum>" option in /etc/ssh/sshd_config. 

You can add the --log-level=debug4 parameter to netconfd to get a more verbose log output.

**Comment by aforester** [comment]
Hi,
I use port 22 (having troubles making port 830 visible, loosing my connectivity to the VM etc).
In the sshd config I have this section:

#NetConf setup
PidFile /run/ssh-netconf.pid
ChallengeResponseAuthentication no
UsePAM yes
AcceptEnv LANG LC_*
PermitRootLogin yes
Port 22
#Port 830
Subsystem netconf "/usr/sbin/netconf-subsystem --ncxserver-sockname=22@/tmp/ncxserver.sock"
#ForceCommand /usr/sbin/netconf-subsystem

I have tried again with the debug4 level and got these messages when doing "connect" (see the attached netconfd-level4.txt).
[netconfd-level4.txt](https://github.com/vlvassilev/yuma123/files/4750723/netconfd-level4.txt)

The same output was obtained for both toaster and helloworld.
Do you think I can avoid this crash just by modifying something about the initial configuration?
Thank you very much!
BR,
Alin

**Comment by vlvassilev** [comment]
I suspect you are missing the --port=22 parameter to netconfd e.g.
`netconfd --no-startup --port=22 --log-level=debug4`
`yangcli --server=localhost --user=vladimir --ncport=22`

If it does not try enabling the -DSES_DEBUG compilation define in netconf/src/ncx/Makefile.am (commented out by default). You should get the following line if everithing is fine:

> ... <ncx-connect xmlns="http://netconfcentral.org/ns/yuma-ncx" version="1" user="vladimir" address="127.0.0.1" magic="x56o8937ab17eg922z34rwhobskdbyswfehkpsqq3i55a0an960ccw24a4ek864aOpal1t2p" transport="ssh" port="22" /> ...

**Comment by aforester** [comment]
Hi Vladimir,

You are right, that was it - I was setting the port on yangcli side only, I thought for netconfd is taken automatically from sshd subsystem configuration.
Now that I set the port for netconfd as well, no more crashes.

Thank you very much!
BR,
Alin
