### ISSUE TITLE
General pointers for database

### ISSUE THREAD

**Issue by aforester** [vlvassilev/yuma123#91]
Hi,

I am struggling to understand and work with Yuma123 project and for this I managed to install it and run few examples.

In my case, as I see it, I will need to create a different client application to actually apply commands and config data into a device, application that will need to communicate with a SIL library which I need to implement and run in netconfd context.

What I fail to understand is about the databases. Are these present in Yuma project, or is it something I need to implement, or both? Are they a specific type, file? I will need to configure the device (commands) and read telemetry (data) and I assume I will really need such databases.

Can you give me a few pointers, where to look, it seems I don't really understand the topology here. 
Any help will be much appreciated!

Thank you!

**Comment by vlvassilev** [comment]
Yes. You usually have client applications (like ifconfig, ethtool, i2c-tool, devmem etc.) that you can call to apply the configuration, read status or call rpc. But you can also read and write using ioctl calls or use any other inter-process communication. It is up to the specific device or application you are writing a SIL for.

You do not need to implement a database. The libyumancx API has functions to access the datastores and the configuration is written to a XML file at every commit transaction.

One example you should look into is example-modules/ietf-network-bridge It implements the YANG model of a flow capable network bridge and uses Openflow device ( openvswitch ). So it has the complete set of configuration, status, notification and RPC primitives demonstrated.

**Comment by aforester** [comment]
Thank you for your reply, it is very helpful!

I will look into that example, if you could leave this ticket open for another day or two, it would be great!
Best regards,
Alin

**Comment by aforester** [comment]
I have a question, only marginally related to database.

In the toaster example, there is this operation "yangcli joe@localhost> xget /toaster"
This "toaster" is represented in YANG file as a container with 3 leafs: manufacturer, model, status.
In this example we get the toaster related data from that container (with some values hardcoded in SIL, I suppose in normal case we should read them from database(?)), although there is no RPC defined for this. Is this something we can do in general when we want to read "read-only"data (with "config false" in YANG file)? Or is it recommended to create an RPC that would retrieve this data? If I would have several containers with ro data, should I make sure to have handlers for all those containers?

I am trying to wrap my head around these notions, sorry for (maybe) trivial questions.

Thank you!

**Comment by vlvassilev** [comment]
"yangcli joe@localhost> xget /toaster"

generates the standard NETCONF RPC <get>

> <get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
>   <filter type="xpath" select="/toaster"/>
> </get>

<get> and <edit-config> are the standard NETCONF RPCs but they were created before YANG and make use of XML attributes e.g. type="xpath" or type="subtree" (see RFC6241). Same concept with <edit-config> This is a problem for yangcli since it is based on YANG. To resolve the issue for the parameter entry <yangcli:xget> and <yangcli:sget>RPCs were added to invoke <get> and <yangcli:create>,<yangcli:merge> and <yangcli:delete> to call <edit-config>. The servers you connect to know nothing about the wrapper virtual RPCs.

So no you do not need private RPCs you will be using <get> and <edit-config>.

**Comment by aforester** [comment]
Thank you very much, I'm still digesting your previous comment, not sure if I understood all of it.

Another question related to built-in server modules. Let's take for example "ietf-netconf-monitoring.yang". If I need some statistics, let's take for example "in-bad-hellos", is that automatically available in database, or do I need to populate that counter?

**Comment by vlvassilev** [comment]
ietf-netconf-monitoring.yang is implemented as part of netconfd.

```
yangcli root@192.168.0.17> xget /
...
      statistics {
        netconf-start-time 2020-07-13T00:10:34Z
        in-bad-hellos 0
        in-sessions 4
...
```

**Comment by aforester** [comment]
I understand, thank you!

Since we are on this (I have looked at the code on how those statistics are retrieved), I will dare to ask further, for example about this function: agt_make_virtual_leaf
In the documentation is stated that "Most device monitoring leafs use this function because the value is retrieved with a device-specific API, not stored in the value tree." Does this mean that the values are not stored in the database, but read from the device directly? As I understand, the "value tree" represents an equivalent of a "snapshot"?

Best regards!

**Comment by lightside-instruments** [comment]
Correct. Only "config true;" data nodes are written in startup-cfg.xml

It is up to implementations to decide if they will be reading the contents of certain "config false;" data nodes from a database or directly from sensors etc.

**Comment by vlvassilev** [comment]
Correct. Only "config true;" data nodes are written in startup-cfg.xml

It is up to implementations to decide if they will be reading the contents of certain "config false;" data nodes from a database or directly from sensors etc.

**Comment by aforester** [comment]
Thank you very much for all the help, it was invaluable.
I will close this ticket now, although it's very likely that I will need your expertise again but on other topics.

Have a nice weekend!
