### ISSUE TITLE
Expired certificate for Wiki?

### ISSUE THREAD

**Issue by aforester** [vlvassilev/yuma123#93]
Hello,

I am not sure where to notify this - I have troubles accessing the wiki pages due to invalid certificate (expired?), I get this error: NET::ERR_CERT_DATE_INVALID
Since in my company there are all sort of checks, I cannot navigate on these pages - can it be fixed?
I apologize if not the right place for this notification.

Thank you!

**Comment by vlvassilev** [comment]
Fixed.
